changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Security
      labels: [security]
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Maintenance
      labels: ['*']
