package io.weave.client.subscription

import java.io.IOException
import java.net.HttpURLConnection
import java.net.InetAddress
import java.net.URI
import java.net.SocketTimeoutException
import javax.net.ssl.HttpsURLConnection

data class SubscriptionFetchResult(
    val body: String,
    val finalUri: URI,
    val contentType: String?,
)

/**
 * Request expanded Walless nodes without forcing the legacy CFA response format. Provider
 * manifests are resolved by ClashProviderResolver, just as CMFA loads their node collections.
 * Only the exact legacy query generated by Weave is migrated; custom/signed queries are retained.
 */
internal object SubscriptionRequestCompatibility {
    // Walless has used several service domains over its lifetime. Keep this allowlist narrow so
    // ordinary subscriptions are never rewritten, while a redirect to an older/newer Walless
    // host keeps the documented expanded-node request.
    private val WALLLESS_ROOTS = setOf(
        "wallesspku.space",
        "wallesspku.org",
        "wallesspku.com",
        "wallesspku.net",
        "walless.top",
        "941321.xyz",
    )

    fun adapt(uri: URI): URI {
        val host = uri.host?.lowercase()?.trimEnd('.') ?: return uri
        if (WALLLESS_ROOTS.none { host == it || host.endsWith(".$it") }) return uri

        val components = uri.rawQuery.orEmpty().split('&').filter(String::isNotEmpty)
        val legacy = components.toSet() == setOf("client=cfa", "provider=false", "cluster=false") ||
            components.toSet() == setOf("client=cfa", "provider=false")
        val kept = if (legacy) components.filterNot { it == "client=cfa" || it == "provider=false" } else components
        val present = kept.joinToString("&")
            .split('&')
            .asSequence()
            .mapNotNull { component ->
                component.substringBefore('=', missingDelimiterValue = component)
                    .takeIf(String::isNotEmpty)
                    ?.lowercase()
            }
            .toSet()
        val additions = buildList {
            // Walless aggregates several physical servers into one advertised node by default.
            // Request its documented expanded view; never override an explicit user choice.
            if ("cluster" !in present) add("cluster=false")
        }
        if (additions.isEmpty() && !legacy) return uri

        // Do not append after a fragment. URI fragments are rejected by the normal URL policy,
        // but keeping this helper structurally correct also protects callers that use it before
        // validation (and avoids accidentally moving an anchor into the query string).
        val base = uri.toString().substringBefore('#').substringBefore('?')
        val fragment = uri.rawFragment?.let { "#$it" }.orEmpty()
        return URI(base + "?" + (kept + additions).joinToString("&") + fragment)
    }
}

/**
 * Small HTTPS-only fetcher with bounded redirects and response size.
 *
 * Redirects are handled manually so every hop is revalidated and an HTTPS subscription can never
 * silently downgrade to cleartext or pivot to a loopback/private literal.
 */
class SafeSubscriptionFetcher(
    private val urlPolicy: SubscriptionUrlPolicy = SubscriptionUrlPolicy(),
    private val maxBytes: Int = DEFAULT_MAX_BYTES,
    private val maxRedirects: Int = DEFAULT_MAX_REDIRECTS,
    private val resolver: (String) -> Array<InetAddress> = InetAddress::getAllByName,
    private val connectionFactory: (URI) -> HttpsURLConnection = { uri ->
        uri.toURL().openConnection() as? HttpsURLConnection
            ?: throw SubscriptionImportException("订阅连接不是 HTTPS")
    },
) {
    fun fetch(rawUrl: String, adaptMainSubscription: Boolean = true): SubscriptionFetchResult {
        var current = urlPolicy.validate(rawUrl)

        repeat(maxRedirects + 1) { hop ->
            // Apply this before every hop so a Walless redirect remains in expanded-node mode while
            // unrelated hosts and explicitly supplied parameters stay untouched.
            // Provider URLs already identify a concrete node file. Main-subscription query
            // compatibility flags must never be appended to a provider request.
            val compatible = if (adaptMainSubscription) SubscriptionRequestCompatibility.adapt(current) else current
            if (compatible != current) {
                current = urlPolicy.validate(compatible.toString())
            }
            // Honor the process route, including an already-working VPN. Binding exclusively
            // to physical networks made protected/blocked provider downloads fail and bypassed
            // the user's selected tunnel. Never silently bypass another VPN during import.
            val response = fetchHop(current)
            when (response.status) {
                HttpURLConnection.HTTP_OK -> {
                    return SubscriptionFetchResult(
                        body = requireNotNull(response.body),
                        finalUri = current,
                        contentType = response.contentType,
                    )
                }

                HttpURLConnection.HTTP_MOVED_PERM,
                HttpURLConnection.HTTP_MOVED_TEMP,
                HttpURLConnection.HTTP_SEE_OTHER,
                307,
                308,
                -> {
                    if (hop == maxRedirects) {
                        throw SubscriptionImportException("订阅重定向次数过多")
                    }
                    val location = response.location
                        ?: throw SubscriptionImportException("订阅重定向缺少目标地址")
                    current = urlPolicy.validate(current.resolve(location).toString())
                }

                else -> throw SubscriptionImportException("订阅服务器返回 HTTP ${response.status}")
            }
        }

        throw SubscriptionImportException("订阅重定向次数过多")
    }

    private data class HopResponse(
        val status: Int,
        val body: String? = null,
        val contentType: String? = null,
        val location: String? = null,
    )

    private fun fetchHop(uri: URI): HopResponse = try {
        urlPolicy.validateResolvedAddresses(uri, resolver)
        executeHop(uri)
    } catch (error: SocketTimeoutException) {
        throw SubscriptionImportException("订阅服务器连接超时，请检查当前网络或暂时关闭其他 VPN 后重试", error)
    } catch (error: IOException) {
        throw SubscriptionImportException("无法连接订阅服务器，请检查当前网络或暂时关闭其他 VPN 后重试", error)
    }

    private fun executeHop(uri: URI): HopResponse {
        val connection = connectionFactory(uri)
        try {
            connection.instanceFollowRedirects = false
            connection.connectTimeout = CONNECT_TIMEOUT_MS
            connection.readTimeout = READ_TIMEOUT_MS
            connection.requestMethod = "GET"
            connection.useCaches = false
            connection.setRequestProperty(
                "Accept",
                "application/yaml, text/yaml, text/plain, application/json, */*",
            )
            // Keep the response bytes directly parseable. Some Android URL stacks do not
            // transparently decode gzip streams when a custom Network is used, which would
            // otherwise turn a valid Clash document into an invalid UTF-8 import.
            connection.setRequestProperty("Accept-Encoding", "identity")
            connection.setRequestProperty("User-Agent", SubscriptionClientIdentity.USER_AGENT)
            connection.setRequestProperty("Cache-Control", "no-cache, no-transform")

            return when (val status = connection.responseCode) {
                HttpURLConnection.HTTP_OK -> {
                    val declared = connection.contentLengthLong
                    if (declared > maxBytes) {
                        throw SubscriptionImportException("订阅内容超过 ${maxBytes / 1024} KiB 限制")
                    }
                    val body = connection.inputStream.use {
                        SubscriptionResponseBody.read(it, connection.contentEncoding, maxBytes)
                    }
                    HopResponse(
                        status = status,
                        body = body,
                        contentType = connection.contentType,
                    )
                }

                HttpURLConnection.HTTP_MOVED_PERM,
                HttpURLConnection.HTTP_MOVED_TEMP,
                HttpURLConnection.HTTP_SEE_OTHER,
                307,
                308,
                -> HopResponse(
                    status = status,
                    location = connection.getHeaderField("Location"),
                )

                else -> throw SubscriptionImportException("订阅服务器返回 HTTP $status")
            }
        } finally {
            connection.disconnect()
        }
    }

    private companion object {
        const val DEFAULT_MAX_BYTES = 5 * 1024 * 1024
        const val DEFAULT_MAX_REDIRECTS = 3
        const val CONNECT_TIMEOUT_MS = 10_000
        const val READ_TIMEOUT_MS = 15_000
    }
}
